apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sprint-planning
  description: Sprint Planning
  annotations:
    github.com/project-slug: 
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
